import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import { useRouter } from 'next/router';
import { useEffect } from 'react';
import styles from '../styles/Home.module.css'
import {getParkings , updateParking , createParking} from './controllers/parking.controller'
import {getCarOwners , register , login , updateUser} from './controllers/user.controller'

const Home: NextPage = () => {
  const route = useRouter()
  useEffect(()=>{
    route.push('/login')
  },[])

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      

      {/* <button onClick={createParking}>create parking</button>
      <button onClick={updateParking}>update parking</button>

      <button onClick={register}>register user</button>
      <button onClick={login}>login user</button>
      <button onClick={updateUser}>update user</button> */}
    </div>
  )
}

export default Home
